# Generated by Django 3.2.12 on 2022-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_book_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanedbooks',
            old_name='book_num',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='wishes',
            old_name='book_num',
            new_name='book_name',
        ),
        migrations.AlterField(
            model_name='applications',
            name='application_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanedbooks',
            name='loan_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='wish_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
