# Generated by Django 3.2.12 on 2022-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_loanedbooks_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedbooks',
            name='return_state',
            field=models.CharField(choices=[('L', 'Loaned'), ('P', 'Pending'), ('R', 'Returned'), ('O', 'Overdue')], max_length=1),
        ),
    ]
