# Generated by Django 3.2.12 on 2022-03-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.books'),
        ),
    ]
