# Generated by Django 3.2.12 on 2022-03-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedbooks',
            name='return_state',
            field=models.CharField(choices=[('L', 'Loaned'), ('E', 'Extended'), ('P', 'Pending'), ('R', 'Returned'), ('O', 'Overdue')], max_length=1),
        ),
    ]
