# Generated by Django 3.2.12 on 2022-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20220325_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanedbooks',
            name='point',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
