# Generated by Django 3.2.12 on 2022-03-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_loanedbooks_return_state'),
        ('books', '0005_auto_20220325_1353'),
    ]

    operations = [
    ]
