# Generated by Django 3.2.12 on 2022-03-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_loanedbooks_point'),
        ('books', '0006_merge_20220329_1047'),
    ]

    operations = [
    ]
