# Generated by Django 3.2.12 on 2022-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_merge_0006_loanedbooks_point_0006_merge_20220329_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loanedbooks',
            name='point',
            field=models.IntegerField(blank=True),
        ),
    ]