# Generated by Django 3.2.12 on 2022-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_loanedbooks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='confirm_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
