# Generated by Django 3.2.12 on 2022-02-09 02:22

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(help_text='입력예) 010-1234-1234', max_length=15, validators=[django.core.validators.RegexValidator('^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$', message='양식에 맞춰 휴대폰번호를 입력해주세요 EX) 010-1234-1234')]),
        ),
    ]
