# Generated by Django 3.2.12 on 2022-04-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_alter_user_point'),
    ]

    operations = [
    ]
