# Generated by Django 3.2.12 on 2022-03-14 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_num', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(db_index=True, max_length=50)),
                ('player_num', models.CharField(db_index=True, max_length=10)),
                ('play_time', models.CharField(db_index=True, max_length=10)),
                ('level', models.CharField(db_index=True, max_length=10)),
                ('game_rule', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임 목록',
                'ordering': ['-game_num'],
            },
        ),
        migrations.CreateModel(
            name='LoanedGame',
            fields=[
                ('loan_game_num', models.AutoField(primary_key=True, serialize=False)),
                ('laned_time', models.DateTimeField()),
                ('return_due_time', models.DateTimeField()),
                ('returned_time', models.DateTimeField()),
                ('return_state', models.CharField(choices=[('L', 'Loaned'), ('R', 'Returned')], max_length=1)),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaned_game', to='game.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게임 대여',
                'verbose_name_plural': '대여 게임 목록',
                'ordering': ['-loan_game_num'],
            },
        ),
    ]
