# Generated by Django 3.2.12 on 2022-03-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_cover_photo',
            field=models.ImageField(blank=True, upload_to='books/%Y/%M'),
        ),
    ]
