# Generated by Django 3.2.12 on 2022-03-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_game_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanedgame',
            old_name='laned_time',
            new_name='loaned_time',
        ),
    ]
