# Generated by Django 3.2.12 on 2022-03-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_laned_time_loanedgame_loaned_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Borrowed')], default='A', max_length=1),
        ),
    ]
