# Generated by Django 3.2.12 on 2022-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedgame',
            name='loaned_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
