# Generated by Django 3.2.12 on 2022-03-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_loanedgame_loaned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedgame',
            name='loaned_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanedgame',
            name='return_due_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='loanedgame',
            name='returned_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
