# Generated by Django 3.2.12 on 2022-03-22 05:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20220317_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_review_num', models.AutoField(primary_key=True, serialize=False)),
                ('game_review_content', models.CharField(db_index=True, max_length=100)),
                ('game_review_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('game_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게임 리뷰',
                'verbose_name_plural': '게임 리뷰 목록',
                'ordering': ['-game_review_num'],
            },
        ),
    ]
