# Generated by Django 3.2.12 on 2022-03-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedgame',
            name='loaned_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanedgame',
            name='return_due_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loanedgame',
            name='returned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
