# Generated by Django 3.2.12 on 2022-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20220323_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedgame',
            name='return_due_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanedgame',
            name='returned_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
