# Generated by Django 3.2.12 on 2022-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20220323_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedgame',
            name='return_due_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loanedgame',
            name='returned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
