# Generated by Django 3.2.12 on 2022-03-25 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20220324_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedgame',
            name='return_due_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
