# Generated by Django 3.2.12 on 2022-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_loanedgame_return_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanedgame',
            name='return_due_time',
            field=models.DateTimeField(),
        ),
    ]
