# Generated by Django 3.2.12 on 2022-04-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='play_time',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
