# Generated by Django 3.2.12 on 2022-04-13 06:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_cover_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='books/%Y/%M'),
        ),
    ]
